const PAGE_CHANGE = 'PAGE_CHANGE';
const PAGE_CHANGE_SUCCEED = 'PAGE_CHANGE_SUCCEED';
const PAGE_CHANGE_ERROR = 'PAGE_CHANGE_ERROR';

const TEST_SAGA = 'TEST_SAGA';
const TEST_SAGA_SUCCEED = 'TEST_SAGA_SUCCEED';
const TEST_SAGA_ERROR = 'TEST_SAGA_ERROR';

const GET_ACTIVITIES = 'GET_ACTIVITIES';
const GET_ACTIVITIES_SUCCEED = 'GET_ACTIVITIES_SUCCEED';
const GET_ACTIVITIES_ERROR = 'GET_ACTIVITIES_ERROR';

const GET_GROUPS = 'GET_GROUPS';
const GET_GROUPS_SUCCEED = 'GET_GROUPS_SUCCEED';
const GET_GROUPS_ERROR = 'GET_GROUPS_ERROR';

const ADD_ACTIVITY = 'ADD_ACTIVITY';
const ADD_ACTIVITY_SUCCEED = 'ADD_ACTIVITY_SUCCEED';
const ADD_ACTIVITY_ERROR = 'ADD_ACTIVITY_ERROR';

const EDIT_ACTIVITY = 'EDIT_ACTIVITY';
const EDIT_ACTIVITY_SUCCEED = 'EDIT_ACTIVITY_SUCCEED';
const EDIT_ACTIVITY_ERROR = 'EDIT_ACTIVITY_ERROR';

const GET_ACTIVITY_BY_ID = 'GET_ACTIVITY_BY_ID';
const GET_ACTIVITY_BY_ID_SUCCEED = 'GET_ACTIVITY_BY_ID_SUCCEED';
const GET_ACTIVITY_BY_ID_ERROR = 'GET_ACTIVITY_BY_ID_ERROR';

const ADD_GROUP = 'ADD_GROUP';
const ADD_GROUP_SUCCEED = 'ADD_GROUP_SUCCEED';
const ADD_GROUP_ERROR = 'ADD_GROUP_ERROR';

const EDIT_GROUP = 'EDIT_GROUP';
const EDIT_GROUP_SUCCEED = 'EDIT_GROUP_SUCCEED';
const EDIT_GROUP_ERROR = 'EDIT_GROUP_ERROR';

const DELETE_GROUP = 'DELETE_GROUP';
const DELETE_GROUP_SUCCEED = 'DELETE_GROUP_SUCCEED';
const DELETE_GROUP_ERROR = 'DELETE_GROUP_ERROR';

const SOCKET_CONNECT = 'SOCKET_CONNECT';
const SOCKET_CONNECT_SUCCEED = 'SOCKET_CONNECT_SUCCEED';
const SOCKET_CONNECT_ERROR = 'SOCKET_CONNECT_ERROR';

const BIND_ROBOT_2_GROUP = 'BIND_ROBOT_2_GROUP';
const BIND_ROBOT_2_GROUP_SUCCEED = 'BIND_ROBOT_2_GROUP_SUCCEED';
const BIND_ROBOT_2_GROUP_ERROR = 'BIND_ROBOT_2_GROUP_ERROR';

const GET_GROUP_DETAIL = 'GET_GROUP_DETAIL';
const GET_GROUP_DETAIL_SUCCEED = 'GET_GROUP_DETAIL_SUCCEED';
const GET_GROUP_DETAIL_ERROR = 'GET_GROUP_DETAIL_ERROR';

const UPDATE_ROBOT_4_GROUP = 'UPDATE_ROBOT_4_GROUP';
const UPDATE_ROBOT_4_GROUP_SUCCEED = 'UPDATE_ROBOT_4_GROUP_SUCCEED';
const UPDATE_ROBOT_4_GROUP_ERROR = 'UPDATE_ROBOT_4_GROUP_ERROR';

const GET_ROBOTS_LIST = 'GET_ROBOTS_LIST';
const GET_ROBOTS_LIST_SUCCEED = 'GET_ROBOTS_LIST_SUCCEED';
const GET_ROBOTS_LIST_ERROR = 'GET_ROBOTS_LIST_ERROR';

const SAVE_ROBOT = 'SAVE_ROBOT';
const SAVE_ROBOT_SUCCEED = 'SAVE_ROBOT_SUCCEED';
const SAVE_ROBOT_ERROR = 'SAVE_ROBOT_ERROR';

const GET_ACTIVITY_TAG = 'GET_ACTIVITY_TAG';
const GET_ACTIVITY_TAG_SUCCEED = 'GET_ACTIVITY_TAG_SUCCEED';
const GET_ACTIVITY_TAG_ERROR = 'GET_ACTIVITY_TAG_ERROR';

const GET_GROUP_TAG = 'GET_GROUP_TAG';
const GET_GROUP_TAG_SUCCEED = 'GET_GROUP_TAG_SUCCEED';
const GET_GROUP_TAG_ERROR = 'GET_GROUP_TAG_ERROR';

const GET_UNBIND_GROUP = 'GET_UNBIND_GROUP';
const GET_UNBIND_GROUP_SUCCEED = 'GET_UNBIND_GROUP_SUCCEED';
const GET_UNBIND_GROUP_ERROR = 'GET_UNBIND_GROUP_ERROR';

const UPDATE_ROBOT = 'UPDATE_ROBOT';
const UPDATE_ROBOT_SUCCEED = 'UPDATE_ROBOT_SUCCEED';
const UPDATE_ROBOTP_ERROR = 'UPDATE_ROBOTP_ERROR';

export default {
  PAGE_CHANGE,
  PAGE_CHANGE_SUCCEED,
  PAGE_CHANGE_ERROR,
  TEST_SAGA,
  TEST_SAGA_SUCCEED,
  TEST_SAGA_ERROR,
  GET_ACTIVITIES,
  GET_ACTIVITIES_SUCCEED,
  GET_ACTIVITIES_ERROR,
  GET_GROUPS,
  GET_GROUPS_SUCCEED,
  GET_GROUPS_ERROR,
  ADD_ACTIVITY,
  ADD_ACTIVITY_SUCCEED,
  ADD_ACTIVITY_ERROR,
  EDIT_ACTIVITY,
  EDIT_ACTIVITY_SUCCEED,
  EDIT_ACTIVITY_ERROR,
  GET_ACTIVITY_BY_ID,
  GET_ACTIVITY_BY_ID_SUCCEED,
  GET_ACTIVITY_BY_ID_ERROR,
  ADD_GROUP,
  ADD_GROUP_SUCCEED,
  ADD_GROUP_ERROR,
  EDIT_GROUP,
  EDIT_GROUP_SUCCEED,
  EDIT_GROUP_ERROR,
  DELETE_GROUP,
  DELETE_GROUP_SUCCEED,
  DELETE_GROUP_ERROR,
  SOCKET_CONNECT,
  SOCKET_CONNECT_SUCCEED,
  SOCKET_CONNECT_ERROR,
  BIND_ROBOT_2_GROUP,
  BIND_ROBOT_2_GROUP_SUCCEED,
  BIND_ROBOT_2_GROUP_ERROR,
  GET_GROUP_DETAIL,
  GET_GROUP_DETAIL_SUCCEED,
  GET_GROUP_DETAIL_ERROR,
  UPDATE_ROBOT_4_GROUP,
  UPDATE_ROBOT_4_GROUP_SUCCEED,
  UPDATE_ROBOT_4_GROUP_ERROR,
  GET_ROBOTS_LIST,
  GET_ROBOTS_LIST_SUCCEED,
  GET_ROBOTS_LIST_ERROR,
  SAVE_ROBOT,
  SAVE_ROBOT_SUCCEED,
  SAVE_ROBOT_ERROR,
  GET_ACTIVITY_TAG,
  GET_ACTIVITY_TAG_SUCCEED,
  GET_ACTIVITY_TAG_ERROR,
  GET_GROUP_TAG,
  GET_GROUP_TAG_SUCCEED,
  GET_GROUP_TAG_ERROR,
  GET_UNBIND_GROUP,
  GET_UNBIND_GROUP_SUCCEED,
  GET_UNBIND_GROUP_ERROR,
  UPDATE_ROBOT,
  UPDATE_ROBOT_SUCCEED,
  UPDATE_ROBOTP_ERROR,
}